Mountaindrew/urls.py
"""Mountaindrew URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('landing.app_urls', 'landing'), namespace='landing')),
    path('blog/', include('blog.blog_urls', namespace='blog'))
]

about/models.py
from django.db import models


class Job(models.Model):
    job_title = models.CharField(max_length=64)
    start_date = models.DateField(blank=True)  # TODO will this cause problems for camp etc?
    end_date = models.DateField(blank=True)
    supervisor = models.CharField(max_length=64, blank=True)
    description = models.TextField(blank=True)
    company_id = models.ForeignKey('Organization', on_delete=models.SET_DEFAULT, default=1)
    display_on_site = models.BooleanField()

    def __str__(self):
        return self.job_title


class Organization(models.Model):
    name = models.CharField(max_length=64)
    address_line_one = models.CharField(max_length=128, blank=True)
    city = models.CharField(max_length=32, blank=True)
    state = models.CharField(max_length=2, blank=True)
    years_affiliated = models.CharField(max_length=64, blank=True)  # for descriptive times <1 year, every summer, etc.

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name


class JobDetail(models.Model):
    PYTHON = 0
    SQL = 1
    MONGO = 2
    POSTMAN = 3
    LINUX = 4

    SKILL_CHOICES = [
        (PYTHON, 'Python'),
        (SQL, 'SQL'),
        (MONGO, 'MongoDB'),
        (POSTMAN, 'Postman'),
        (LINUX, 'Linux')
    ]

    job_id = models.ForeignKey('Job', on_delete=models.CASCADE)
    skills = models.IntegerField(choices=SKILL_CHOICES)
    description = models.TextField()

blog/models.py
import re

from django.db import models


class Category(models.Model):
    date_created = models.DateTimeField()
    last_updated = models.DateTimeField()
    name = models.CharField(max_length=16)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    is_published = models.BooleanField()
    date_created = models.DateTimeField()
    last_updated = models.DateTimeField()
    date_published = models.DateTimeField(null=True, blank=True)

    title = models.CharField(max_length=64)
    content = models.TextField()
    category = models.ManyToManyField(Category, verbose_name="Category Tag", blank=True)

    class Meta:
        ordering = ['-date_published', '-date_created']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.cleaned_content = self._clean_content()

    def _clean_content(self):
        """
        Remove HTML tags and markdown ticks for clean copy of content
        :return:
        """
        return re.sub('```\w*', '', re.sub('<.*>', '', self.content))

    def get_preview(self):
        if len(self.cleaned_content) >= 200:
            return f'{self.cleaned_content[:197]}...'
        else:
            return self.content

    def get_categories(self):
        return [tag['name'] for tag in self.category.values()]

    def is_edited(self):
        time_diff = self.last_updated - self.date_published
        # Seconds are not cumulative
        return (time_diff.seconds > 2 * 60) or (time_diff.days > 0)

    def __str__(self):
        return self.title

landing/models.py
from django.db import models


class Job(models.Model):
    # job_id = models.AutoField(primary_key=True)
    job_title = models.CharField(max_length=64)
    start_date = models.DateField(blank=True)  # TODO will this cause problems for camp etc?
    end_date = models.DateField(blank=True)
    supervisor = models.CharField(max_length=64, blank=True)
    description = models.TextField(blank=True)
    company_id = models.ForeignKey('Company', on_delete=models.SET_DEFAULT, default=1)
    display_on_site = models.BooleanField()

    def __str__(self):
        return self.job_title


class Company(models.Model):
    # id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)
    address_line_one = models.CharField(max_length=128, blank=True)
    city = models.CharField(max_length=32, blank=True)
    state = models.CharField(max_length=2, blank=True)
    years_affiliated = models.CharField(max_length=64, blank=True)  # for descriptive times <1 year, every summer, etc.

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name

about/views.py
from django.views.generic import ListView

from about.models import Job, JobDetail


class JobListView(ListView):
    template_name = 'about/index.html'
    context_object_name = 'job'
    model = Job

    def get_queryset(self):
        _queryset = super().get_queryset()
        return [p for p in _queryset if p.display_on_site]

blog/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView

from blog import models


class BlogListView(ListView):
    template_name = 'blog/list.html'
    context_object_name = 'all_blogs'
    model = models.BlogPost
    paginate_by = 5

    def get_queryset(self):
        my_queryset = super().get_queryset()
        return [p for p in my_queryset if p.is_published]


class SingleBlogView(DetailView):
    template_name = 'blog/single.html'
    context_object_name = 'blog_post'
    model = models.BlogPost

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_published:
            raise Http404()
        return obj

landing/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'landing/index.html', context=None)


def cv(request):
    return render(request, 'landing/cv.html', context=None)

templates/about/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titler %}
    <title>About ME</title>
{% endblock %}
{% block add_css %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock %}

{% block content %}
    <div class="jumbotron">


        <div class="">
            <h1 class="text-center">Resume</h1>
            {% for jerb in job %}
                <div class="card">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card-body">
                                <h6 class="card-title">{{ jerb.company_id }}</h6>
                                <p class="card-text small">{{ jerb.company_id.address_line_one }}</p>
                                <p class="card-text small">{{ jerb.company_id.city }}, {{ jerb.company_id.state }}</p>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {{ jerb.job_title }}
                                </h5>
                                <p class="card-text">
                                    {{ jerb.description }}
                                </p>
                                <ul>
                                    {% for detail in jerb.jobdetail_set.all %}
                                        <li>
                                            <p class="card-text small">
                                                {{ detail.description }}
                                            </p>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>


        <div class="music">
            <h1 class="text-center">Music</h1>

            <div class="container-fluid soundcloud">
                <div class="row">
                    <div class="col-4">
                        <p class="soundcloud quote">
                            I play guitar and bass mostly, but when I'm at home I like to use the power of a computer.
                            Here are a few things I've finished. Usually the final mixing/mastering takes the most time.
                        </p>
                    </div>
                    <div class="col-8">
                        <ul class="list-group ">
                            <li class="list-group-item">
                                <iframe class="soundcloud frame"
                                        src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/681888461&color=%23ff5500&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false">
                                </iframe>
                            </li>
                            <li class="list-group-item">
                                <iframe class="soundcloud frame"
                                        src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/681889592&color=%23ff5500&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false">
                                </iframe>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

<script src="{% static "/js/about.js" %}"></script>

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {# For Mobile? #}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block titler %}
        {#Default value if no "titler" block is present in child template#}
        <title>Mountain Drew</title>
    {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/override_general.css" %}"/>
    {% block add_css %}
    {% endblock %}
</head>


<body class="main-1">


{#NAVBAR#}
<nav class="navbar navbar-expand-sm navbar-light bg-light">

    <a class="navbar-brand" href="{% url 'landing:index' %}"><img title="Home"
                                                                  style="width: 50px;"
                                                                  src="{% static 'img/mountain-outline.svg' %}"
                                                                  alt="Mountain Drew"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"><a class="nav-link" href="{% url 'blog:Blog' %}">Blog</a></li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Connect With Me
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://github.com/aduncan314">Github</a>
                    <a class="dropdown-item" href="https://www.linkedin.com/in/andrew-duncan-5b2b24188/">LinkedIn</a>
                </div>
            </li>
        </ul>

    </div>
</nav>


{#MAIN CONTENT - BACKGROUND AND BLOCK#}
<div class="main-blob">

    <img src="{% static "img/mountain-outline.svg" %}" class="background-img" width="100%" height="500">
    <div class="row main-padding">
        <div class="col-md-2"></div>


        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>

        <div class="col-md-2"></div>
    </div>
</div>


{#SCRIPTS#}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static "/js/override_general.js" %}"></script>

</body>
</html>

templates/blog/base_blog.html
{% extends 'base.html' %}
{% load static %}

{% block titler %}
    <title>All Blogs Go To Heaven</title>
{% endblock %}

{#Additional css for python formatting#}
{% block add_css %}
<link rel="stylesheet" href="{% static 'css/default.css' %}">
<link rel="stylesheet" href="{% static 'css/pygment.css' %}">
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="text-center">All Blogs Go to Heaven</h1>
    </div>
    {% block blog %}{% endblock %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base_blog.html' %}
{% load static %}
{% load pygment_filter %}


{% block blog %}
    {#        PAGINATION        #}
    {#    TODO: rewrite with JS using only one GET     #}
    {% if is_paginated %}
        <div aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="/blog?page={{ page_obj.previous_page_number }}"
                           aria-label="previous">&laquo</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-disabled="true">&laquo</a>
                    </li>
                {% endif %}
                {% for num in paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active">
                            <a class="page-link" href="/blog?page={{ num }}">{{ num }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="/blog?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="/blog?page={{ page_obj.next_page_number }}"
                           aria-label="next">&raquo</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#"
                           aria-disabled="true">&raquo</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}


    {#    CARDS     #}

    <ul class="list-unstyled">
        {% for post in all_blogs %}
            <li class="card m-2">
                <div class="card-header">
                    <a class="h4" href="{{ post.id }}">{{ post.title }}  </a>
                    <small class="text-muted">{{ post.date_published }}</small>
                    <div class="d-flex flex-row-reverse">
                        {% for tag in post.get_categories %}
                            <span class="p-2 badge badge-secondary" style="margin: 0.5%;">
                                        {{ tag }}
                                    </span>
                        {% endfor %}
                    </div>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ post.get_preview|markdown|safe }}</p>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/blog/single.html
{% extends 'blog/base_blog.html' %}
{% load static %}
{% load pygment_filter %}

{% block blog %}
    <div class="jumbotron">
        <h1 class="text-center">{{ blog_post.title }}</h1>
        <p class="text-md-right">Published: {{ blog_post.date_published }}</p>
        {% if blog_post.is_edited %}
            <p class="text-md-right text-muted">Edited: {{ blog_post.last_updated }}</p>
        {% endif %}
        <hr>
        <p>{{ blog_post.content|markdown|safe|linebreaks }}</p>
    </div>
{% endblock %}

templates/landing/cv.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container main-blob">
        <div class="myb jumbotron border border-dark">
            <h1 class="text-center display-4">Resume/CV</h1>
        </div>
        <div id="cv-section" class="container-fluid">
            <div class="row p-4">

                <div class="col-md border border-primary rounded text-center p-2">
                    <button type="button" id="pdf" onclick="ChooseThis(id)" class="btn btn-primary p-4">
                        Download pdf resume
                    </button>
                </div>

                <div class="col-md border border-primary rounded text-center p-2">
                    <button type="button" id="html" onclick="ChooseThis(id)" class="btn btn-primary p-4">
                        View resume
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static '/js/override_general.js' %}"></script>
{% endblock %}

templates/landing/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="myb jumbotron border border-dark">
        <h1 class="display-3 text-center">Mountain Drew</h1>
        <hr>
        <hr>
        <p>Hi, I am Drew. I am a Boston-based developer who enjoys working with data, databases, APIs, and other hidden
            parts of an application that keep it running.</p>
        <p>For the past two years I wrote python everyday and <a href="https://xkcd.com/2054/">managed data
            pipelines</a> for an ed tech company. Before that, I taught <a href="https://xkcd.com/2117/">AP Calc</a> and
            other math courses at a charter school in Everett. I graduated with a BS in <a
                    href="https://xkcd.com/410/">Math</a> and <a href="https://xkcd.com/1240/">Physics</a> from UMass
            Boston.</p>
        <p>This site is built with nginx/gunicorn/Django and uses Bootstrap to keep things simple. I’ll be writing
            about this and other work on my <a href="{% url 'blog:Blog' %}">blog</a>.</p>
        <p>When I am not programming, I am probably playing bass in my classic rock cover band, playing with synths,
            climbing a rock, or <span data-toggle="tooltip"
                                      title="This is my wife's commentary">finding another hobby that involves lots of gear.</span>
        </p>
    </div>
    <script>function f() {
        ('[data-toggle="tooltip"]').tooltip()
    }</script>


{% endblock %}